config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get  '/signup',  to: 'users#new'  
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :users, only: [:new, :create, :show]
  resources :events, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :attendees, through: :invitations
  has_many :invitations, foreign_key: "attended_event_id"

  scope :upcoming, -> { where("date >= ?", Time.zone.now).order("date ASC") }
  scope :past, -> { where("date < ?", Time.zone.now).order("date DESC") }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attended_event, class_name: "Event"
  belongs_to :attendee,  class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  before_save :downcase_email

  # validates :name, presence: true, length: { maximum: 50 },
  #                  uniqueness: { case_sensitive: true}
  # validates :email, presence: true, length: { maximum: 255 },
  #                   format: { with: VALID_EMAIL_REGEX },
  #                   uniqueness: { case_sensitive: false }
  
  has_many :created_events, foreign_key: "creator_id", class_name: "Event"
  has_many :invitations, foreign_key: "attendee_id"
  has_many :attended_events, through: :invitations

  def upcoming_events
    self.attended_events.where("date >= ?", Time.zone.now)
  end

  def previous_events
    self.attended_events.where("date < ?", Time.zone.now)
  end

  private

    def downcase_email
      email.downcase!
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

  private

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        # store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      flash[:success] = 'A new event was created'
      redirect_to events_path
    else
      render :new
    end
  end

  private

    def event_params
      params.require(:event).permit(:detail, :location, :date, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(name: params[:session][:name])
    if @user
      session[:user_id] = user.id
      flash[:success] = "Welcome, #{@user.name}, you are now logged in"
      redirect_to root_path
    else
      flash.now[:danger] = "Try again with another name"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil 
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the party zone!"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = current_user.upcoming_events
    @prev_events = current_user.previous_events
  end

  private

    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end
  end

  def logged_in?
    !current_user.nil?   
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_event.html.erb
<li>
  <p><b><%= event.detail %></b></p>
  <p><%= event.description %></p>
  <p>Date: <%= event.date %></p>
  <p>Location: <%= event.location %></p>
  <p>Hosted by <%= User.find(event.creator_id).name %></p>
</li>

app/views/events/index.html.erb
<h1>All Events</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <p>Upcoming events:</p>
    <ul><%= render @events.upcoming %></ul>
    <p>Past events:</p>
    <ul><%= render @events.past %></ul>
  </div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :detail %>
      <%= f.text_field :detail, class: 'form-control' %>
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control' %>
      <%= f.label :date %>
      <%= f.datetime_select :date, :ampm => true, 
                            :minute_step => 15,
                            :start_year => Time.now.year,
                            :start_month => Time.now.month,
                            :start_day => Time.now.day,
                            class: 'form-control'
                             %>
      <%= f.hidden_field :creator_id, value: current_user.id %>
      <%= f.submit "Let's Party!", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<h1>Event Info</h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <p><h3><%= @event.detail %></h3></p>
    <p><h3><%= @event.description %></h3></p>
    <p><h3>Hosed by: <%= User.find(@event.creator_id).name %></h3></p>
    <% if @event.attendees.any? %>
      <% @event.attendees.each do |attendee| %>
        <ul>
          <li><%= attendee.name %></li>
        </ul>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "private events", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Events", events_path %></li>
        <li><%= link_to "New Event", new_event_path %></li>
        <% if logged_in? %>
          <li><a href='#'><%= @current_user.name %></a></li>
          <li><%= link_to "Log out", logout_path %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% flash.each do |type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{type}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_event.html.erb
<tr>
  <td><%= "#{event.date.month}-#{event.date.day}-#{event.date.year}" %></td>
  <td><%= event.detail %></td>
<tr>

app/views/users/new.html.erb
<h1>New User Sign Up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>  
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.submit "Sign Up", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>User Info</h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <p><h3><%= @user.name %></h3></p>
    <p><h3><%= @user.email %></h3></p>
    <h2>My hosted events:</h2>
    <table>
      <% if @my_events.any? %>
        <% @my_events.each do |event| %>
          <%= render 'event', event: event %>
        <% end %>
      <% end %>
    </table>
    <h2>Upcomming Events:</h2>
    <table>
      <% if @upcoming_events.any? %>
        <% @upcoming_events.each do |coming_event| %>
          <%= render 'event', event: coming_event %>
        <% end %>
      <% end %>
    </table>
    <h2>Past Events:</h2>
    <table>
      <% if @prev_events.any? %>
        <% @prev_events.each do |past_event| %>
          <%= render 'event', event: past_event %>
        <% end %>
      <% end %>
    </table>      
  </div>
</div>

app/views/welcome/home.html.erb
<h1>Welcome to the Party Zone</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h3>Here is a simple application to schedule parties, so login and join the party!</h3>
  </div>
</div>